### ISSUE TITLE
Wrong locale

### ISSUE THREAD

**Issue by YellowLooksRed** [unattended-ch/ytdlg#15]
Seems like the Windows Setup file doesn't properly adjust to system locale. I have English set as my system language but setup still displays in German(?)

**Comment by unattended-ch** [comment]
Will be fixed in v0.0.0.24

Thanks for your support.
I have forgotten to add more languages to NSIS, now all available languages are implemented.

**Comment by unattended-ch** [comment]
v0.0.0.24 is available.
