### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by KalpanaChetan** [unattended-ch/ytdlg#24]
![2.png](https://user-images.githubusercontent.com/112402936/208957188-4cde82dc-45e0-401e-a5df-bda63caae896.png)

**Comment by unattended-ch** [comment]
Hy KalpanaChetan,

Please click on button <I>, and send  the error from yt-dlp.

Depending on available formats it helps to change output from mp4 to mkv.

**Comment by unattended-ch** [comment]
Hy KalpanaChetan,

I have tried this download without problems.

Have you clicked on \<Tools> for the needed tools during setup ?
Otherways you must already have installed yt-dlp, ffmpeg and mutagen.
If NOT run setup again an click on \<Tools> and it will work.

**Comment by KalpanaChetan** [comment]
![Screenshot (5).png](https://user-images.githubusercontent.com/112402936/209254652-2f1bf8f1-398e-4dd0-b832-99de6484d336.png)





![Screenshot (6).png](https://user-images.githubusercontent.com/112402936/209254686-f1fbedc0-bbb9-4b6c-a3a3-c353d803d504.png)



![Screenshot (7).png](https://user-images.githubusercontent.com/112402936/209254702-7bff13a0-69eb-4c70-91d5-c18af61850f5.png)



![Screenshot (8).png](https://user-images.githubusercontent.com/112402936/209254746-6bf14ae0-9450-4b11-8c99-ef29e925fe0b.png)

**Comment by KalpanaChetan** [comment]
> Hy KalpanaChetan,
> 
> Please click on button \<I>, and send  the error from yt-dlp.
> 
> Depending on available formats it helps to change output from mp4 to mkv.






How can i send you the error file 

None of the option in github

**Comment by KalpanaChetan** [comment]
![Screenshot (9).png](https://user-images.githubusercontent.com/112402936/209255491-d2fed8d1-0349-4f2e-8e49-98d8c78699d1.png)

**Comment by unattended-ch** [comment]
> How can i send you the error file

You can open data001.err with your editor, then copy and paste it as text here...

- It looks like you have tried befor with an older version ytdlg (existing dataXXX.err).  These files are replaced with dataXXX.dbg since v0.0.0.30.

1. You must reset the download by \<Right-Click> on \<I> button and press \<Reset>.
2. To activate the changes press \<F12>. After restart, try again.

**Comment by KalpanaChetan** [comment]
ERROR: [generic] 'nahi\\Videos' is not a valid URL. Set --default-search "ytsearch" (or run  yt-dlp "ytsearch:nahi\Videos" ) to search YouTube
[youtube] BT78Rd3hGG0: Downloading webpage
[youtube] BT78Rd3hGG0: Downloading android player API JSON
[info] BT78Rd3hGG0: Downloading 1 format(s): 248+251
ERROR: unable to create directory [WinError 5] Access is denied: 'C:\\Users\\pata'
ERROR: unable to create directory [WinError 5] Access is denied: 'C:\\Users\\pata'

**Comment by KalpanaChetan** [comment]
![Screenshot (11).png](https://user-images.githubusercontent.com/112402936/209276534-fe41637f-ee14-4ed6-836a-3cf3978e13a6.png)

**Comment by KalpanaChetan** [comment]
[error.zip](https://github.com/unattended-ch/ytdlg/files/10292324/error.zip)

**Comment by KalpanaChetan** [comment]
please download and extract the error zip

**Comment by unattended-ch** [comment]
> error.zip

This ist the content of dataXXX.info. And looks correct.
In your APPDATA folder you have data001.err and data002.err, these files are important.

> ERROR: [generic] 'nahi\Videos' is not a valid URL. Set --default-search "ytsearch" (or run yt-dlp "ytsearch:nahi\Videos" ) to search YouTube

This occours if you not specify https://...

Please remove all dataXXX.nnn files and reaload the URL.

**Comment by KalpanaChetan** [comment]
[data error.zip](https://github.com/unattended-ch/ytdlg/files/10295325/data.error.zip)

**Comment by KalpanaChetan** [comment]
![Screenshot (24)](https://user-images.githubusercontent.com/112402936/209345324-57f465bf-0d07-423c-b2d7-b4f75ef2a1f6.png)


![Screenshot (25)](https://user-images.githubusercontent.com/112402936/209345355-8874c575-9de6-42eb-bb3c-a27d0267c23a.png)

**Comment by KalpanaChetan** [comment]
[New Compressed (zipped) Folder.zip](https://github.com/unattended-ch/ytdlg/files/10295396/New.Compressed.zipped.Folder.zip)

**Comment by KalpanaChetan** [comment]
[New Compressed (zipped) Folder.zip](https://github.com/unattended-ch/ytdlg/files/10295422/New.Compressed.zipped.Folder.zip)

**Comment by unattended-ch** [comment]
Uninstall ytdlg and remove data in %APPDATA%.
Clear registry key /HKCU/Software/unattended.ch/ytdlg...
Install ytdlg latest version.

Closing for now.
