### ISSUE TITLE
[Bug]: error reading json report

### ISSUE THREAD

**Issue by cyberhardt** [unattended-ch/ytdlg#27]
### What happened?

after conventional setup, a "error: failed reading json data" message appeared every time I tried to load a video. it asks me to delete .info, which i did, but the error keeps popping up. windows 10 22h2

### Version

0.0.0.33 (Latest)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unattended-ch** [comment]
"error: failed reading json data" says that yt-dlp was executed and now json record with information was found.

Please read [yt-dlp Supported Sites](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) for more information.

YTDLG is only the GUI for yt-dlp, and if it was executed the GUI can do nothing.

**Comment by Reviem0** [comment]
I get the same error as soon as I open dlg
I don't input anything and still get the error
I tried putting a youtube video in and also get the error
